//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CariUnvan_Firma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CariUnvan_Firma()
        {
            this.Tartim = new HashSet<Tartim>();
            this.Tartim1 = new HashSet<Tartim>();
            this.Tartim2 = new HashSet<Tartim>();
        }
    
        public int CariUnvan_FirmaId { get; set; }
        public string CariUnvan_FirmaAd { get; set; }
        public string CariUnvan_FirmaTelefon { get; set; }
        public string CariUnvan_FirmaAdres { get; set; }
        public string CariUnvan_FirmaEmail { get; set; }
        public string CariUnvan_FirmaVergiDairesi { get; set; }
        public string CariUnvan_FirmaVergiNo { get; set; }
        public string CariUnvan_FirmaMarsisNo { get; set; }
        public string CariUnvan_SahisAdSoyad { get; set; }
        public string CariUnvan_SahisAd { get; set; }
        public string CariUnvan_SahisSoyad { get; set; }
        public string CariUnvan_FirmaTC { get; set; }
        public Nullable<bool> CariUnvan_FirmaGonderici { get; set; }
        public Nullable<int> CariUnvan_FirmaTip { get; set; }
        public string Il { get; set; }
        public string Ilce { get; set; }
        public Nullable<bool> Arsiv { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tartim> Tartim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tartim> Tartim1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tartim> Tartim2 { get; set; }
    }
}
