//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WindowsFormsApp1Entities : DbContext
    {
        public WindowsFormsApp1Entities()
            : base("name=WindowsFormsApp1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Arac> Arac { get; set; }
        public virtual DbSet<CariUnvan_Firma> CariUnvan_Firma { get; set; }
        public virtual DbSet<Malzeme> Malzeme { get; set; }
        public virtual DbSet<SevkYeri> SevkYeri { get; set; }
        public virtual DbSet<Sofor> Sofor { get; set; }
        public virtual DbSet<Tartim> Tartim { get; set; }
        public virtual DbSet<Yetkili> Yetkili { get; set; }
    }
}
