//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tartim
    {
        public int TartimId { get; set; }
        public Nullable<int> AracId { get; set; }
        public Nullable<int> IslemSirasi { get; set; }
        public Nullable<System.DateTime> OlcumTarihi { get; set; }
        public Nullable<int> CariUnvan_FirmaAliciId { get; set; }
        public Nullable<int> MalzemeId { get; set; }
        public Nullable<int> SevkYeriId { get; set; }
        public Nullable<int> SoforId { get; set; }
        public Nullable<double> BrutAgirlik { get; set; }
        public Nullable<double> AracAgirlik { get; set; }
        public Nullable<double> NetAgirlik { get; set; }
        public Nullable<double> Ucret { get; set; }
        public Nullable<int> CariUnvan_FirmaNakliyeciId { get; set; }
        public Nullable<int> CariUnvan_FirmaGondericiId { get; set; }
        public Nullable<int> YetkiliId { get; set; }
    
        public virtual Arac Arac { get; set; }
        public virtual CariUnvan_Firma CariUnvan_Firma { get; set; }
        public virtual CariUnvan_Firma CariUnvan_Firma1 { get; set; }
        public virtual CariUnvan_Firma CariUnvan_Firma2 { get; set; }
        public virtual Malzeme Malzeme { get; set; }
        public virtual SevkYeri SevkYeri { get; set; }
        public virtual Sofor Sofor { get; set; }
        public virtual Yetkili Yetkili { get; set; }
    }
}
